"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision = ${repr(revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}

def upgrade():
    ${upgrades if upgrades else "# ### commands auto generated by Alembic - please adjust! ###\n    pass\n    # ### end Alembic commands ###"}

def downgrade():
    ${downgrades if downgrades else "# ### commands auto generated by Alembic - please adjust! ###\n    pass\n    # ### end Alembic commands ###"}