"""add_task_dependencies_table

Revision ID: 3a628d53d4b6
Revises: 007_add_ideation_system
Create Date: 2026-01-07 22:29:29.113925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a628d53d4b6'
down_revision = '007_add_ideation_system'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create task_dependencies table (idempotent)
    op.execute("""
        CREATE TABLE IF NOT EXISTS task_dependencies (
            task_id INTEGER NOT NULL,
            depends_on_id INTEGER NOT NULL,
            PRIMARY KEY (task_id, depends_on_id),
            FOREIGN KEY(depends_on_id) REFERENCES tasks(id) ON DELETE CASCADE,
            FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE
        )
    """)
    op.drop_index('ix_daily_reports_user_date', table_name='daily_reports')
    op.drop_constraint('daily_reports_user_id_fkey', 'daily_reports', type_='foreignkey')
    op.create_foreign_key(None, 'daily_reports', 'users', ['user_id'], ['id'])
    op.drop_index('ix_ideation_messages_project_created', table_name='ideation_messages')
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.add_column('veille_results', sa.Column('result_type', sa.Enum('FUNDING_OPPORTUNITY', 'TECH_ARTICLE', 'TECH_TOOL', 'EVENT', 'COLLABORATION', 'ACADEMIC_PAPER', 'NEWS_ARTICLE', 'ARTIST_WORK', 'CALL_FOR_PROPOSALS', name='veilleresulttype'), nullable=False))
    op.add_column('veille_results', sa.Column('status', sa.Enum('NEW', 'READ', 'SAVED', 'ACTIONABLE', 'DISMISSED', name='veilleresultstatus'), nullable=False))
    op.create_index(op.f('ix_veille_results_result_type'), 'veille_results', ['result_type'], unique=False)
    op.create_index(op.f('ix_veille_results_status'), 'veille_results', ['status'], unique=False)
    op.add_column('veille_topics', sa.Column('scope', sa.Enum('TECH', 'FUNDING', 'CULTURAL', 'ACADEMIC', 'NEWS', 'COLLABORATION', name='veillescope'), nullable=False))
    op.create_index(op.f('ix_veille_topics_scope'), 'veille_topics', ['scope'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop task_dependencies table
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_veille_topics_scope'), table_name='veille_topics')
    op.drop_column('veille_topics', 'scope')
    op.drop_index(op.f('ix_veille_results_status'), table_name='veille_results')
    op.drop_index(op.f('ix_veille_results_result_type'), table_name='veille_results')
    op.drop_column('veille_results', 'status')
    op.drop_column('veille_results', 'result_type')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.create_index('ix_ideation_messages_project_created', 'ideation_messages', ['project_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'daily_reports', type_='foreignkey')
    op.create_foreign_key('daily_reports_user_id_fkey', 'daily_reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_daily_reports_user_date', 'daily_reports', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###