"""fix_maturity_score_migration

Revision ID: bb168b82f5c5
Revises: 3a628d53d4b6
Create Date: 2026-01-08 01:57:41.842654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb168b82f5c5'
down_revision = '3a628d53d4b6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('maturity_score', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'maturity_score')
    # ### end Alembic commands ###