"""add_model_preferences_to_user_settings

Revision ID: dfb94a7cfccc
Revises: bb168b82f5c5
Create Date: 2026-01-09 00:46:47.702154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb94a7cfccc'
down_revision = 'bb168b82f5c5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values for existing rows
    op.add_column('user_settings', sa.Column('ollama_model_ideation', sa.String(length=255), nullable=False, server_default='mistral:7b-instruct-q4_K_M'))
    op.add_column('user_settings', sa.Column('ollama_model_analysis', sa.String(length=255), nullable=False, server_default='mistral:7b-instruct-q4_K_M'))
    op.add_column('user_settings', sa.Column('ollama_model_task_generation', sa.String(length=255), nullable=False, server_default='mistral:7b-instruct-q4_K_M'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'ollama_model_task_generation')
    op.drop_column('user_settings', 'ollama_model_analysis')
    op.drop_column('user_settings', 'ollama_model_ideation')
    # ### end Alembic commands ###